name: FSL SHACL Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pySHACL
        run: |
          pip install pyshacl

      - name: Run Validation
        run: |
          cd validation
          make

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: validation/*.log